# Generated by Django 3.1.4 on 2020-12-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myboard', '0002_auto_20201216_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task'},
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(1, 'New'), (2, 'In progress'), (3, 'In QA'), (4, 'Ready'), (5, 'Done')], default=1, max_length=300),
        ),
    ]
