# Generated by Django 3.1.4 on 2020-12-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myboard', '0003_auto_20201220_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN PR', 'In progress'), ('IN QA', 'In QA'), ('READY', 'Ready'), ('DONE', 'Done')], default='NEW', max_length=300),
        ),
    ]
