# Generated by Django 3.1.4 on 2020-12-21 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myboard', '0004_auto_20201220_0704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created'], 'verbose_name': 'Task'},
        ),
    ]
