# Generated by Django 3.1.4 on 2020-12-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myboard', '0006_auto_20201223_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'In Prog'), (3, 'In Qa'), (4, 'Ready'), (5, 'Done')], default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
